# Generated by Django 5.0 on 2023-12-21 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='full_name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
